# Generated by Django 4.1.2 on 2022-11-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_profile_follower_alter_profile_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
    ]
