# Generated by Django 4.1.2 on 2022-11-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_profile_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follower',
        ),
    ]
